// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zaj9.Models;

namespace zaj9.Migrations
{
    [DbContext(typeof(ProbkiDb))]
    [Migration("20200517131918_druga")]
    partial class druga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("zaj9.Models.Lab", b =>
                {
                    b.Property<int>("IDLAB")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaLab")
                        .IsRequired()
                        .HasColumnName("NAZWALAB")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("iloscPracownikow")
                        .HasColumnType("int");

                    b.HasKey("IDLAB");

                    b.ToTable("Lab");

                    b.HasData(
                        new
                        {
                            IDLAB = 1,
                            NazwaLab = "ZTM",
                            iloscPracownikow = 6
                        },
                        new
                        {
                            IDLAB = 2,
                            NazwaLab = "GRC",
                            iloscPracownikow = 15
                        },
                        new
                        {
                            IDLAB = 3,
                            NazwaLab = "MTU",
                            iloscPracownikow = 7
                        });
                });

            modelBuilder.Entity("zaj9.Models.Probki", b =>
                {
                    b.Property<int>("IdBadania")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdBadania")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FkLab")
                        .HasColumnName("FK_LAB")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_Pojemnikow")
                        .HasColumnType("int");

                    b.Property<decimal>("Kosztbadania")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nazwa_Probki")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<double>("Waga_Probek")
                        .HasColumnType("float");

                    b.Property<bool>("zbadane")
                        .HasColumnType("bit");

                    b.HasKey("IdBadania");

                    b.HasIndex("FkLab");

                    b.ToTable("Probki");
                });

            modelBuilder.Entity("zaj9.Models.Probki", b =>
                {
                    b.HasOne("zaj9.Models.Lab", "Lab")
                        .WithMany("Probki")
                        .HasForeignKey("FkLab");
                });
#pragma warning restore 612, 618
        }
    }
}
